# Generated by Django 5.2.9 on 2025-12-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudtable',
            name='profile_pic',
            field=models.URLField(default='empty'),
        ),
    ]
